// Mocks generated by Mockito 5.4.6 from annotations
// in magic_rewards/test/unit_test/features/home/data/repositories/home_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/src/foundation/diagnostics.dart' as _i3;
import 'package:magic_rewards/features/home/data/datasources/home_datasource.dart'
    as _i4;
import 'package:magic_rewards/features/home/data/models/home_model.dart' as _i2;
import 'package:magic_rewards/features/home/domain/parameters/home_parameters.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeModel_0 extends _i1.SmartFake implements _i2.HomeModel {
  _FakeHomeModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [HomeDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeDataSource extends _i1.Mock implements _i4.HomeDataSource {
  MockHomeDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.HomeModel> getHome(_i6.HomeParameters? parameters) =>
      (super.noSuchMethod(
            Invocation.method(#getHome, [parameters]),
            returnValue: _i5.Future<_i2.HomeModel>.value(
              _FakeHomeModel_0(this, Invocation.method(#getHome, [parameters])),
            ),
          )
          as _i5.Future<_i2.HomeModel>);
}
