// Mocks generated by Mockito 5.4.6 from annotations
// in riverpod_rewards/test/unit_test/features/auth/data/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter/src/foundation/diagnostics.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_rewards/features/auth/data/datasources/local/user_local_data_source.dart'
    as _i10;
import 'package:riverpod_rewards/features/auth/data/datasources/remote/auth_datasource.dart'
    as _i5;
import 'package:riverpod_rewards/features/auth/data/models/check_email_model.dart'
    as _i4;
import 'package:riverpod_rewards/features/auth/data/models/user_model.dart'
    as _i2;
import 'package:riverpod_rewards/features/auth/domain/entities/user_entity.dart'
    as _i11;
import 'package:riverpod_rewards/features/auth/domain/parameters/check_email_parameters.dart'
    as _i9;
import 'package:riverpod_rewards/features/auth/domain/parameters/login_parameters.dart'
    as _i7;
import 'package:riverpod_rewards/features/auth/domain/parameters/register_parameters.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeCheckEmailModel_1 extends _i1.SmartFake
    implements _i4.CheckEmailModel {
  _FakeCheckEmailModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [IAuthDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthDataSource extends _i1.Mock implements _i5.IAuthDataSource {
  MockIAuthDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.UserModel> login(_i7.LoginParameters? parameters) =>
      (super.noSuchMethod(
            Invocation.method(#login, [parameters]),
            returnValue: _i6.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#login, [parameters])),
            ),
          )
          as _i6.Future<_i2.UserModel>);

  @override
  _i6.Future<_i2.UserModel> register(_i8.RegisterParameters? parameters) =>
      (super.noSuchMethod(
            Invocation.method(#register, [parameters]),
            returnValue: _i6.Future<_i2.UserModel>.value(
              _FakeUserModel_0(
                this,
                Invocation.method(#register, [parameters]),
              ),
            ),
          )
          as _i6.Future<_i2.UserModel>);

  @override
  _i6.Future<_i4.CheckEmailModel> checkEmail(
    _i9.CheckEmailParameters? parameters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmail, [parameters]),
            returnValue: _i6.Future<_i4.CheckEmailModel>.value(
              _FakeCheckEmailModel_1(
                this,
                Invocation.method(#checkEmail, [parameters]),
              ),
            ),
          )
          as _i6.Future<_i4.CheckEmailModel>);
}

/// A class which mocks [UserLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalDataSource extends _i1.Mock
    implements _i10.UserLocalDataSource {
  MockUserLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveUserData(_i11.UserEntity? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [user]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i11.UserEntity?> getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i6.Future<_i11.UserEntity?>.value(),
          )
          as _i6.Future<_i11.UserEntity?>);
}
